### ISSUE TITLE
Add click Event for MouseEvent support

### ISSUE THREAD

**Issue by Sw0rdiX** [jannicz/appointment-picker#17]
https://github.com/jannicz/appointment-picker/blob/eec8b73274ac08fce5d50d4cd5c49a921da41d79/js/appointment-picker.js#L99

u can add here click support for mouse

`el.addEventListener('click', _this.openEventFn);`

**Comment by jannicz** [comment]
@Sw0rdiX, please confirm that solution on https://github.com/jannicz/appointment-picker/pull/18 would fix your problem!

**Comment by Sw0rdiX** [comment]
@jannicz, i confirm that the solution on #18 fix my problem.
