### ISSUE TITLE
Add a case to the valid check

### ISSUE THREAD

**Issue by Sw0rdiX** [jannicz/appointment-picker#21]
https://github.com/jannicz/appointment-picker/blob/3289e99b3cbef900e85b8633e12cd40af7d41414/js/appointment-picker.js#L319

> maxTime sets the maximum hour that can be picked, default is 24

it mean that e.g 9 is set that 9:15 cannot be picked or ? 

if yes, add please this check (hour === opt.maxTime && minute) for the intervals, in the moment u can pick 9:00 as last maxTime is correct, but not the 9:[intervals].
`     } else if(hour === opt.maxTime && minute > 0){`

**Comment by jannicz** [comment]
@Sw0rdiX indeed, you are right. Fix is on the way...
