### ISSUE TITLE
Can we select time slots in range?

### ISSUE THREAD

**Issue by hamzabinamin** [jannicz/appointment-picker#25]
is it possible to select two time slots to make up a time range?

**Comment by jannicz** [comment]
Thanks for the feedback, in this implementation it is not possible to select time ranges. A workaround could be to use 2 timepickers for start and end inputs and implement your own validation.

But there is a fork of this repository where multiple timeslot picking was implemented, see https://github.com/grandadmiralmcb/appointment-picker or download
https://www.npmjs.com/package/appointment-slot-picker

Considered closed.
